export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
